### ISSUE TITLE
Convert project cards to issues

### ISSUE THREAD

**Issue by rlmckenney** [loisaleghe/project1#3]
Hi team,

It looks like you have some good user stories on your Kanban board.  I would suggest that you convert those cards to issues. You can then apply issue labels to them (for example MVP / Future). This will let you more easily sort or filter them.

You will still be able to see them on the Kanban board, but you can now do more with them, including linking them to commits as you complete the implementation for each feature. You will also be able to assign each issue to a team member and track who is working on what.

As you complete the work and close each issue, you can see some overall completion stats.

**Comment by christopherjbourque** [comment]
Thanks for the suggestion.  Done!
